WIP: Implement blinded credential presentation
hpicrypto/kvac pull request #31
Opened 2023-02-14 17:41 UTC by j-hellenberg

2023-02-20 17:05 UTC, leonschmidt99 reviewed
Overall very nice work on this!

2023-02-20 19:56 UTC, konradh commented on kvac/kvac.py
> +    def present(self, *, issuer_key: IssuerPublicKey, hiding_keys: List[HidingKeyPair]) -> CredentialPresentation:
The asterisk indicates the end of positional parameters. All parameters after it can only be given in keyword form. I think it makes sense to use it for publicly exposed APIs because it minimizes the chance to confuse positions of arguments.

2023-02-20 21:04 UTC, konradh commented on kvac/kvac.py
> +    def obtain_tag(self, *, response: IssuanceResponse):
Here the `*` does not make sense, as there is only one argument. I also find the name a bit strange. It exposes to much detail, I think. `activate` would indicate the state change of the credential (now, presentation is allowed).

2023-02-20 21:54 UTC, konradh commented
From my testing, it seems that credentials without hidden attributes no longer work. I always get an error that the issuance response proof is not correct.

2023-02-20 22:01 UTC, konradh requested changes
I don't know why, but if the max attribute number of the system parameters is larger than the number of attributes in the credential, the issuance response proof generation fails (proof does not verify). In my opinion, everything should work if the maximum number is larger than the actual number.

2023-02-21 09:38 UTC, maxthure commented
Could you please bump up the version once this is merged? :) Thx!

2023-02-21 10:16 UTC, merged

2023-02-21 10:19 UTC, j-hellenberg commented
> Could you please bump up the version once this is merged? :) Thx!

Done :)